LIS.UI/Controllers/BillController.cs
using LIS.Model.Models;
using LIS.Model.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LIS.UI.Controllers
{

    public class BillController : Controller
    {
        private _IAllRepository<tblbill> billobj;
        private _IAllRepository<tblpatient> patientobj;
        private _IAllRepository<tblrecord> recordobj;
        private _IAllRepository<tbltestmaster> testmasterobj;
        public BillController()
        {
            billobj = new ClassAllRepository<tblbill>();
            patientobj = new ClassAllRepository<tblpatient>();
            recordobj = new ClassAllRepository<tblrecord>();
            testmasterobj = new ClassAllRepository<tbltestmaster>();

        }
        // GET: Bill
        public ActionResult Index()
        {
            return View(billobj.GetAll());
        }

        // GET: Bill/Details/5
        public ActionResult Details(int id)
        {
            //    


            return View(billobj.GetById(id));
        }

        // GET: Bill/Create
        public ActionResult Create()
        {
            LissystemEntities db = new LissystemEntities();
            var patientvar = patientobj.GetAll();
            ViewBag.list = new SelectList(patientvar, "patientid", "patientfirstname");

            return View();
        }

        // POST: Bill/Create
        [HttpPost]
        public ActionResult Create(tblbill bill)
        {
            try
            {
                // TODO: Add insert logic here
                billobj.Insert(bill);
                billobj.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Bill/Edit/5
        public ActionResult Edit(int id)
        {
            var patientvar = patientobj.GetAll();
            ViewBag.list = new SelectList(patientvar, "patientid", "patientfirstname");
            var bill = billobj.GetById(id);
            return View(bill);

        }

        // POST: Bill/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, tblbill bill)
        {
            try
            {
                // TODO: Add update logic here
                billobj.Update(bill);
                billobj.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Bill/Delete/5
        public ActionResult Delete(int id)
        {
            billobj.Delete(id);
            billobj.Save();
            return RedirectToAction("Index");
        }

        //// POST: Bill/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        public JsonResult getRecordIdFromPatient(int id)
        {
            var data = recordobj.GetAll().Where(d => d.patientid == id);
            var chk = data.Select(t => t.testid);
            var chkarrayString = chk.ToList();

            var anotherTmp = chkarrayString[0];

            String[] testidArray = anotherTmp.Split(',');

            int[] ints = Array.ConvertAll(testidArray, int.Parse);

            List<tbltestmaster> returnArray = new List<tbltestmaster>();



            for (var i = 0; i < ints.Length; i++)
            {
                var tbltestmaster = testmasterobj.GetById(Convert.ToInt32(ints[i]));
                returnArray.Add(new tbltestmaster() { testid = Convert.ToInt32(ints[i]), testname = tbltestmaster.testname, testprice = tbltestmaster.testprice });
            }

            return Json(returnArray.ToList(), JsonRequestBehavior.AllowGet);
        }

    }
}

LIS.UI/Views/Bill/Create.cshtml
@model LIS.Model.Models.tblbill

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card card-body breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Generate Bill</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li>
                                <a href="@Url.Action("Index")" class="btn btn-sm btn-info right">
                                    <i class="fa fa-arrow-left"></i> Back
                                </a>
                            </li>

                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Header-->

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "myform" }))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="row">

            <div class="col-xs-12 col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">
                    </div>

                    <div class="card-body col-md-12">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.patientid, "patientid", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-7">
                                @Html.DropDownList("patientid", ViewBag.list as SelectList, "--select--", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.patientid, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        @*<div id="testandprice">

                            </div>*@
                        <div class="form-check">
                            <p>
                                <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                                    Show test
                                </a>

                            </p>
                            <div class="collapse" id="collapseExample">
                                <div class="card card-body">
                                    <div class="alert alert-primary" role="alert">
                                        <div id="testandprice">

                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.totalprice, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.totalprice, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.totalprice, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.generateddate, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.generateddate, new { htmlAttributes = new { @class = "form-control", @Value = DateTime.Today.ToString("dd/MM/yyyy"), @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.generateddate, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*<div class="form-group">
                                @Html.LabelFor(model => model.recordid, "recordid", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("recordid", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.recordid, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-success" />
                                <input type="reset" value="Cancel" class="btn btn-danger" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script type="text/javascript">
                    $(document).ready(function () {
                        //$("#date").datepicker();
                        $('#patientid').change(function () {
                            //getTestFromPatientId
                            $.ajax({
                                url: "/Bill/getRecordIdFromPatient/" + this.value,
                                type: "GET",
                                contentType: "application/json;charset=utf-8",
                                dataType: "json",
                                success: function (result) {
                                    var html = '';
                                    var total = 0;

                                    for (var i = 0; i < result.length; i++) {
                                        var obj = result[i];
                                        html += `<h3> ${obj.testname}-${obj.testprice}</h3>`;
                                        total += obj.testprice;
                                    }
                                    $('#testandprice').html(html);
                                    $('#totalprice').val(total);
                                },
                                error: function (errormessage) {

                                }
                            });
                        });

                    });</script>


<script>
                    $(document).ready(function () {
                        $("#myform").validate({
                            rules: {
                                patientid: {
                                    required: true,

                                },


                            }
                        })
                    })
</script>

LIS.UI/Views/Bill/Details.cshtml
@model LIS.Model.Models.tblbill

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>


    <dl class="dl-horizontal">
        @Html.HiddenFor(Model => Model.patientid)
    </dl>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        var patientid = $('#patientid').val();

        //$("#date").datepicker();

        //getTestFromPatientId
        $.ajax({
            url: "/Bill/getRecordIdFromPatient/" + patientid,
            type: "GET",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                var html = '';
                var html1 = '';
                //  var total = 0;

                for (var i = 0; i < result.length; i++) {
                    var obj = result[i];
                    html += `<h4> ${obj.testname}</h4>`;
                    html1 += `<h4> ${obj.testprice}</h4>`;
                    // total += obj.testprice;
                }
                $('#test').html(html);
                $('#price').html(html1);
                //jQuery('#totalprice').html(total);
            },
            error: function (errormessage) {

            }
        });

    });
</script>


<!DOCTYPE html>
<html>
<head>
    <style>
    </style>
</head>
<body>

    <p>
        <input type="button" value="Print" class="btn btn-danger" onclick="codespeedy()" />
    </p>


    <div class="container" id="bills">
        <div class="card">
            <div class="card-header">



                <div class="row">
                    <div class="col-md-4"> <img src="~/Content/images/download.jpeg" alt="Girl in a jacket" width="150" height="75" /></div>
                    @*<div class="col-md-4 offset-md-4"> @Html.DisplayFor(model => model.generateddate)</div>*@
                </div>
                <center>
                    <div>
                        <h3 class="color-red mb-2">LIS system</h3>
                        <h6> C/o. Surat-4,Gujrat,India, Ph.:0216-7896541/02</h6>
                        <h6 class="color-red mt-2">By Appointment :- Time: 9.00 A.M. to 9.00 P.M. Sunday close</h6>
                        _________________________________________________________________________________________________________
                    </div>
                </center>




            </div>

            <div class="card-body">
                <div class="row mb-4">
                    <div class="col-sm-12">
                        <div class="pull-right"><label>Invoice Date:</label>   @Html.DisplayFor(model => model.generateddate) </div>
                        <h6 class="mb-3">From:LIS system</h6>

                        <div>Email: lissystem.co.in</div>
                        <div>Phone: +91 985 524 6548</div>



                        <!-- /col-md-3 -->




                    </div>
                    &nbsp;&nbsp;
                    <div class="col-sm-6">
                        <h6 class="mb-3">To:</h6>
                        <div>
                            <strong>
                                <dh>
                                    @Html.DisplayFor(model => model.tblpatient.patientfirstname)
                                    @Html.DisplayFor(model => model.tblpatient.patientmiddelname)

                                    @Html.DisplayFor(model => model.tblpatient.patientlastname)

                                </dh>
                            </strong>
                        </div>


                    </div>



                </div>

                <div class="">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th class="center">Bill no</th>
                                <th>Test Name</th>
                                <th>Price</th>
                            </tr>
                        </thead>




                        <tbody>


                            <tr>
                                <td class="center alert" role="alert"> @Html.DisplayFor(model => model.billid)</td>
                                <td id="test" class="left alert" role="alert"></td>
                                <td id="price" class="left alert" role="alert"></td>
                            </tr>
                            </hr>
                            <tr>
                                <td></td>
                                <td class="left">
                                    <strong>Total</strong>
                                </td>
                                <td class="right">
                                    <strong> @Html.DisplayFor(model => model.totalprice)</strong>
                                </td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
          

        </div>
    </div>
    

</body>
</html>
<script type="text/javascript">

    function codespeedy() {
        
        $(".card").print();
    }

</script>

LIS.UI/Views/Bill/Index.cshtml
@model IEnumerable<LIS.Model.Models.tblbill>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<p>
    @Html.ActionLink("Create New", "Create", null, null, new { @class = "btn btn-primary" })
</p>






<div class="card">
    <div class="card-header">
        <div class="card-title">
            Bills
        </div>
    </div>
    <div class="card-body col-md-12">
        <table id="tblequipement" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>
                        Patient Name
                    </th>
                    <th>
                        Total Price
                    </th>
                    <th>
                        Generated Date
                    </th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.tblpatient.patientfirstname)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.totalprice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.generateddate)
                        </td>

                        <td>

                            <a href="@Url.Action("Details","Bill",new { id = item.billid })" class="btn btn-sm btn-success">
                                <i class="fa fa-eye"></i>
                            </a>|
                            <a href="@Url.Action("Delete","Bill",new { id = item.billid })" onclick="return confirm('Are you sure you wish to delete this equipement?');" class="btn btn-sm btn-danger">
                                <i class="fa fa-trash"></i>
                            </a>|

                        </td>
                    </tr>
                }
            </tbody>




        </table>
    </div>
    <div class="card-footer">

    </div>
</div>
<script>
    $(document).ready(function () {
        $('#tblequipement').DataTable();
    });




</script>