LIS.UI/Controllers/CollectorController.cs
using LIS.Model.Models;
using LIS.Model.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LIS.UI.Controllers
{
    public class CollectorController : Controller
    {
        private _IAllRepository<tblcollector> collectorobj;
        public CollectorController()
        {
            collectorobj = new ClassAllRepository<tblcollector>();
        }

        // GET: Collector
        public ActionResult Index()
        {
            return View(collectorobj.GetAll());
        }

        // GET: Collector/Details/5
        public ActionResult Details(int id)
        {
            return View(collectorobj.GetById(id));
        }

        // GET: Collector/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Collector/Create
        [HttpPost]
        public ActionResult Create(tblcollector collector_pera)
        {
            try
            {
                collectorobj.Insert(collector_pera);
                collectorobj.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Collector/Edit/5
        public ActionResult Edit(int id)
        {
            return View(collectorobj.GetById(id));
        }

        // POST: Collector/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, tblcollector collector_pera)
        {
            try
            {
                collectorobj.Update(collector_pera);
                collectorobj.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Collector/Delete/5
        public ActionResult Delete(int id)
        {
            collectorobj.Delete(id);
            collectorobj.Save();
            return RedirectToAction("Index");
        }

        //// POST: Collector/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

LIS.UI/Controllers/DoctorController.cs
using LIS.Model.Models;
using LIS.Model.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LIS.UI.Controllers
{
    public class DoctorController : Controller
    {
        private _IAllRepository<tbldoctor> doctorobj;
        public DoctorController()
        {
            doctorobj = new ClassAllRepository<tbldoctor>();
        }

        // GET: Doctor
        public ActionResult Index()
        {
            return View(doctorobj.GetAll());
        }

        // GET: Doctor/Details/5
        public ActionResult Details(int id)
        {
            return View(doctorobj.GetById(id));
        }

        // GET: Doctor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Doctor/Create
        [HttpPost]
        public ActionResult Create(tbldoctor doctor_pera)
        {
            try
            {
                doctorobj.Insert(doctor_pera);
                doctorobj.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Doctor/Edit/5
        public ActionResult Edit(int id)
        {
            return View(doctorobj.GetById(id));
        }

        // POST: Doctor/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, tbldoctor doctor_pera)
        {
            try
            {
                doctorobj.Update(doctor_pera);
                doctorobj.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Doctor/Delete/5
        public ActionResult Delete(int id)
        {
            doctorobj.Delete(id);
            doctorobj.Save();
            return RedirectToAction("Index");
        }

        //// POST: Doctor/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

LIS.UI/Controllers/RecordController.cs
using LIS.Model.Models;
using LIS.Model.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LIS.UI.Controllers
{
    public class RecordController : Controller
    {
        private _IAllRepository<tblrecord> recordobj;
        private _IAllRepository<tblpatient> patientobj;
        private _IAllRepository<tbldoctor> doctorobj;
        private _IAllRepository<tblcollector> collectorobj;
        private _IAllRepository<tbltestmaster> testmasterobj;

        public RecordController()
        {
            recordobj = new ClassAllRepository<tblrecord>();
            patientobj = new ClassAllRepository<tblpatient>();
            doctorobj = new ClassAllRepository<tbldoctor>();
            collectorobj = new ClassAllRepository<tblcollector>();
            testmasterobj = new ClassAllRepository<tbltestmaster>();
        }

        // GET: Record
        public ActionResult Index()
        {
            //ViewBag.testObj = testmasterobj.GetAll();
            return View(recordobj.GetAll());
        }

        // GET: Record/Details/5
        public ActionResult Details(int id)
        {
            return View(recordobj.GetById(id));
        }

        // GET: Record/Create
        public ActionResult Create()
        {
            var patient_data = patientobj.GetAll();
            ViewBag.list1 = new SelectList(patient_data, "patientid", "patientfirstname");
            var doctor_data = doctorobj.GetAll();
            ViewBag.list2 = new SelectList(doctor_data, "doctorid", "doctorname");
            var collector_data = collectorobj.GetAll();
            ViewBag.list3 = new SelectList(collector_data, "collectorid", "collectorname");
            var testmaster_data = testmasterobj.GetAll();
            ViewBag.list4 = new SelectList(testmaster_data, "testid", "testname");
            return View();
        }

        // POST: Record/Create
        [HttpPost]
        public ActionResult Create(tblrecord record_para)
        {
            try
            {
                record_para.testid = string.Join(",", record_para.testid_Array);

                recordobj.Insert(record_para);
                recordobj.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Record/Edit/5
        public ActionResult Edit(int id)
        {
            var patient_data = patientobj.GetAll();
            ViewBag.list1 = new SelectList(patient_data, "patientid", "patientfirstname");
            var doctor_data = doctorobj.GetAll();
            ViewBag.list2 = new SelectList(doctor_data, "doctorid", "doctorname");
            var collector_data = collectorobj.GetAll();
            ViewBag.list3 = new SelectList(collector_data, "collectorid", "collectorname");

            var abc = recordobj.GetById(id);
            abc.testid_Array = abc.testid.Split(',').ToArray();

            var testmaster_data = testmasterobj.GetAll();
            ViewBag.list4 = new SelectList(testmaster_data, "testid", "testname");
            return View(recordobj.GetById(id));
        }

        // POST: Record/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, tblrecord record_para)
        {
            try
            {
                record_para.testid = string.Join(",", record_para.testid_Array);

                recordobj.Update(record_para);
                recordobj.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Record/Delete/5
        public ActionResult Delete(int id)
        {
            recordobj.Delete(id);
            recordobj.Save();
            return RedirectToAction("Index");
        }

        //// POST: Record/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

LIS.UI/Views/Record/Create.cshtml
@model LIS.Model.Models.tblrecord

<script>
    //$(document).ready(function () {
    //    $('#normaldropdown').chosen();
    //});
</script>

<!--Header-->
<div class="card card-body breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Add record</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li>
                                <a href="@Url.Action("Index")" class="btn btn-sm btn-info right">
                                    <i class="fa fa-arrow-left"></i> Back
                                </a>
                            </li>

                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Header-->


@using (Html.BeginForm(null,null, FormMethod.Post , new { id="myform" })) 
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="row">

            <div class="col-xs-12 col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">

                    </div>
                    <div class="card-body col-md-12">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            <label class="control-label col-md-5" for="patientid">patientfirst name</label> 
                            <div class="col-md-10">
                                @Html.DropDownList("patientid", ViewBag.list1 as SelectList, "-- Select patient --", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.patientid, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-10" for="doctorid">Doctor name
                                <a href="@Url.Action("Create","Doctor")" style="float:right"><i class="menu-icon fa fa-user-plus"></i> Add doctor</a>
                            </label>
                            <div class="col-md-10">
                                @Html.DropDownList("doctorid", ViewBag.list2 as SelectList, "-- Select Dectorname --", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.doctorid, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-10" for="collectorid">Collector name
                                <a href="@Url.Action("Create","Collector")" style="float:right"><i class="menu-icon fa fa-user-plus"></i> Add collector</a>
                            </label>
                            <div class="col-md-10">
                                @Html.DropDownList("collectorid", ViewBag.list3 as SelectList, "-- Select Collectorname --", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.collectorid, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2" for="samplenumber">Sample number</label>
                            <div class="col-md-10 d-flex">
                                @Html.EditorFor(model => model.samplenumber, new { htmlAttributes = new { @class = "form-control", @id = "samplenumber" } })
                                @Html.ValidationMessageFor(model => model.samplenumber, "", new { @class = "text-danger" })

                                <button id="genSampleNumber" class="btn btn-success">Generate</button>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-5" for="date">Date</label>
                            <div class="col-md-5">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.testid, "Test name", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.ListBoxFor(model => model.testid_Array, ViewBag.list4 as SelectList, new { @class = "select-chosen form-control", multiple = "multiple", id = "normaldropdown", selected = "true" })
                                @Html.ValidationMessageFor(model => model.testid, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2" for="priority">Priority</label>
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.priority)
                                    @Html.ValidationMessageFor(model => model.priority, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3" for="status">Status</label>
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.status)
                                    @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-success" />
                                <input type="reset" value="Cancel" class="btn btn-danger" />
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type='text/javascript'>

    $(document).ready(function () {

        //jQuery("#date").datepicker();
        $('#normaldropdown').chosen();
        
        $('#genSampleNumber').on('click', function (e) {
            e.preventDefault();
            var date = new Date();
            var timestamp = date.getTime();

            $('#samplenumber').val(function () {
                
                if ($('#samplenumber').val() != "") {
                    return $('#samplenumber').val() + ',' + timestamp;
                } else {
                    return timestamp;
                }
            });
        })

        $("#myform").validate({
            rules: {
                patientid:
                {
                    required: true,
                },
                doctorid:
                {
                    required: true,
                },
                collectorid:
                {
                    required: true,
                },
                samplenumber:
                {
                    required: true,
                },
                date:
                {
                    required: true,
                },
                normaldropdown:
                {
                    required: true,
                },
                priority:
                {
                    required: true,
                },
                status:
                {
                    required: true,
                },
            }
        });  
    })

         
</script>

LIS.UI/Views/Record/Details.cshtml
@model LIS.Model.Models.tblrecord

    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <center><h4 class="modal-title" id="exampleModalLongTitle">Record Details</h4></center>
                </div>

                <div class="modal-body">
                    <div>
                        <dl class="dl-horizontal">
                            @Html.HiddenFor(model => model.patientid)

                            <dt>
                                @Html.DisplayNameFor(model => model.tblpatient.patientfirstname)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.tblpatient.patientfirstname)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.tbldoctor.doctorname)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.tbldoctor.doctorname)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.tblcollector.collectorname)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.tblcollector.collectorname)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.samplenumber)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.samplenumber)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.date)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.date)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.testid)
                            </dt>

                            <dd>
                                @*@Html.DisplayFor(model => model.testid)*@
                                <div id="testdiv">

                                </div>
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.priority)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.priority)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.status)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.status)
                            </dd>

                        </dl>
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="@Url.Action("Edit","Record",new { id = Model.recordid })" class="btn btn-sm btn-warning">
                        <i class="fa fa-pencil"></i>Edit
                    </a>
                    <a href="@Url.Action("Index")" class="btn btn-sm btn-info right">
                        <i class="fa fa-arrow-left"></i> Back
                    </a>
                </div>
            </div>
        </div>
    </div>

<script>
    $(document).ready(function () {
        jQuery("#exampleModalCenter").modal('show');

        var patientid = $('#patientid').val();

        $.ajax({
            url: "/Patienttestresult/getTestFromPatientId/" + patientid,
            type: "GET",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                var html = '';
                for (var i = 0; i < result.length; i++) {
                    var obj = result[i];
                    html += `<span>${obj.testid} - ${obj.testname}</span><br/>`;
                }
                $('#testdiv').html(html);
            },
            error: function (errormessage) {

            }
        });
    })
</script>

LIS.UI/Views/Record/Index.cshtml
@model IEnumerable<LIS.Model.Models.tblrecord>

<p>
    @Html.ActionLink("Create New", "Create", null, null, new { @class = "btn btn-primary" })
</p>

<div class="card">
    <div class="card-header">
        <div class="card-title">
            Manage Record
        </div>
    </div>
    <div class="card-body col-md-12">
        <table id="tblrecord" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>
                        Patientfirst name
                    </th>
                    <th>
                        Doctor name
                    </th>
                    <th>
                        Collector name
                    </th>
                    <th>
                        Sample number
                    </th>
                    <th>
                        Date
                    </th>
                    <th>
                        Test name
                    </th>
                    <th>
                        Priority
                    </th>
                    <th>
                        Status
                    </th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.tblpatient.patientfirstname)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tbldoctor.doctorname)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tblcollector.collectorname)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.samplenumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.testid)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.priority)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.status)
                        </td>
                        <td>
                            <a href="@Url.Action("Edit","Record",new { id = item.recordid })" class="btn btn-sm btn-warning">
                                <i class="fa fa-pencil"></i>
                            </a>|
                            <a href="@Url.Action("Details","Record",new { id = item.recordid })" class="btn btn-sm btn-success">
                                <i class="fa fa-eye"></i>
                            </a>|
                            <a href="@Url.Action("Delete","Record",new { id = item.recordid })" onclick="return confirm('Are you sure you wish to delete this record ?');" class="btn btn-sm btn-danger">
                                <i class="fa fa-trash"></i>
                            </a>|
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="card-footer">
    </div>
</div>
<script>

    $(document).ready(function () {
        $('#tblrecord').DataTable();
    });
</script>