LIS.UI/Controllers/AnalyticController.cs
using LIS.Model.Models;
using LIS.Model.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LIS.UI.Controllers
{
    public class AnalyticController : Controller
    {

        private _IAllRepository<tblanalytic> analyticobj;
        public AnalyticController()
        {
            analyticobj = new ClassAllRepository<tblanalytic>();
        }

        // GET: Analytic
        public ActionResult Index()
        {
            return View(analyticobj.GetAll());
        }

        // GET: Analytic/Details/5
        public ActionResult Details(int id)
        {
            return View(analyticobj.GetById(id));
        }

        // GET: Analytic/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Analytic/Create
        [HttpPost]
        public ActionResult Create(tblanalytic analytic_pera)
        {
            try
            {
                analyticobj.Insert(analytic_pera);
                analyticobj.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Analytic/Edit/5
        public ActionResult Edit(int id)
        {
            return View(analyticobj.GetById(id));
        }

        // POST: Analytic/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, tblanalytic analytic_pera)
        {
            try
            {
                analyticobj.Update(analytic_pera);
                analyticobj.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Analytic/Delete/5
        public ActionResult Delete(int id)
        {
            analyticobj.Delete(id);
            analyticobj.Save();
            return RedirectToAction("Index");
        }

        //// POST: Analytic/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

LIS.UI/Views/Analytic/Create.cshtml
@model LIS.Model.Models.tblanalytic

<!--Header-->
<div class="card card-body breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Add Analytic</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li>
                                <a href="@Url.Action("Index")" class="btn btn-sm btn-info right">
                                    <i class="fa fa-arrow-left"></i> Back
                                </a>
                            </li>

                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Header-->


@using (Html.BeginForm(null,null, FormMethod.Post , new { id="myform" })) 
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="row">

            <div class="col-xs-12 col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">

                    </div>
                    <div class="card-body col-md-12">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            <label class="control-label col-md-5" for="diagnosisitem">Diagnosisitem</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.diagnosisitem, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.diagnosisitem, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-5" for="value">Value</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.value , new { htmlAttributes = new { @class = "form-control"} })
                                @Html.ValidationMessageFor(model => model.value, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-5" for="minvalue">Minvalue</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.minvalue, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.minvalue, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-5" for="maxvalue">Maxvalue</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.maxvalue, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.maxvalue, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-5" for="measurementunit">Measurement unit</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.measurementunit, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.measurementunit, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-success" />
                                <input type="reset" value="Cancel" class="btn btn-danger" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type='text/javascript'>
    //jQuery(function () {
    //    jQuery("#date").datepicker();

    //});

    $(document).ready(function () {

        $("#myform").validate({
            rules: {
                diagnosisitem:
                {
                    required: true,
                    maxlength: 40,
                },
                //value:
                //{
                //    required: true,
                //    number: true,
                //},
                minvalue:
                {
                    required: true,
                     number:true,
                },
                maxvalue:
                {
                    required: true,
                     number:true,
                },
                measurementunit:
                {
                    required: true,
                },
            }
        });
    })
</script>

LIS.UI/Views/Analytic/Details.cshtml
@model LIS.Model.Models.tblanalytic

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <center><h4 class="modal-title" id="exampleModalLongTitle">Analytic Details</h4></center>
            </div>

            <div class="modal-body">
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.diagnosisitem)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.diagnosisitem)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.value)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.value)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.minvalue)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.minvalue)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.maxvalue)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.maxvalue)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.measurementunit)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.measurementunit)
                        </dd>

                    </dl>
                </div>
            </div>
            <div class="modal-footer">
                <a href="@Url.Action("Edit","Analytic",new { id = Model.analyticid })" class="btn btn-sm btn-warning">
                    <i class="fa fa-pencil"></i>Edit
                </a>
                <a href="@Url.Action("Index")" class="btn btn-sm btn-info right">
                    <i class="fa fa-arrow-left"></i> Back
                </a>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(document).ready(function () {
        jQuery("#exampleModalCenter").modal('show');
    });
</script>

LIS.UI/Views/Analytic/Edit.cshtml
@model LIS.Model.Models.tblanalytic

<!--Header-->
<div class="card card-body breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Modify Analytic</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li>
                                <a href="@Url.Action("Index")" class="btn btn-sm btn-info right">
                                    <i class="fa fa-arrow-left"></i> Back
                                </a>
                            </li>

                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Header-->


@using (Html.BeginForm(null,null, FormMethod.Post , new { id="myform" })) 
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="row">

            <div class="col-xs-12 col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">

                    </div>
                    <div class="card-body col-md-12">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model=>model.analyticid)

                        <div class="form-group">
                            <label class="control-label col-md-5" for="diagnosisitem">Diagnosisitem</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.diagnosisitem, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.diagnosisitem, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-5" for="value">Value</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.value, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.value, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-5" for="minvalue">Minvalue</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.minvalue, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.minvalue, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-5" for="maxvalue">Maxvalue</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.maxvalue, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.maxvalue, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-5" for="measurementunit">Measurement unit</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.measurementunit, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.measurementunit, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Update" class="btn btn-success" />
                                <input type="reset" value="Cancel" class="btn btn-danger" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


<script type='text/javascript'>

    $(document).ready(function () {

        $("#myform").validate({
            rules: {
                diagnosisitem:
                {
                    required: true,
                    maxlength: 15,
                },
                //value:
                //{
                //    required: true,
                //    number:true,
                //},
                minvalue:
                {
                    required: true,
                     number:true,
                },
                maxvalue:
                {
                    required: true,
                     number:true,
                },
                measurementunit:
                {
                    required: true,
                },
            }
        });
    })
</script>

LIS.UI/Views/Analytic/Index.cshtml
@model IEnumerable<LIS.Model.Models.tblanalytic>

<p>
    @Html.ActionLink("Create New", "Create", null, null, new { @class = "btn btn-primary" })
</p>
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Manage Test
        </div>
    </div>
    <div class="card-body col-md-12">
        <table id="tblanalytic" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>
                        Diagnosisitem
                    </th>
                    <th>
                        Value
                    </th>
                    <th>
                        Minvalue
                    </th>
                    <th>
                        Maxvalue
                    </th>
                    <th>
                        Measurementunit
                    </th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.diagnosisitem)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.value)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.minvalue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.maxvalue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.measurementunit)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit","Analytic",new { id = item.analyticid })" class="btn btn-sm btn-warning">
                            <i class="fa fa-pencil"></i>
                        </a>|
                        <a href="@Url.Action("Details","Analytic",new { id = item.analyticid })" class="btn btn-sm btn-success">
                            <i class="fa fa-eye"></i>
                        </a>|
                        <a href="@Url.Action("Delete","Analytic",new { id = item.analyticid })" onclick="return confirm('Are you sure you wish to delete this analytic ?');" class="btn btn-sm btn-danger">
                            <i class="fa fa-trash"></i>
                        </a>|
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="card-footer">
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#tblanalytic').DataTable();
    });
</script>